site_name: Unity ML-Agents Toolkit
site_url: https://unity-technologies.github.io/ml-agents/
repo_url: https://github.com/Unity-Technologies/ml-agents
edit_uri: edit/main/docs/
site_description: "DEPRECATED: This documentation has been moved to the Unity Package Documentation. Please visit https://docs.unity3d.com/Packages/com.unity.ml-agents@latest for current documentation. The Unity Machine Learning Agents Toolkit (ML-Agents) is an open-source project that enables games and simulations to serve as environments for training intelligent agents."
site_author: Unity Technologies
copyright: com.unity.ml-agents copyright © 2017 - 2022 Unity Technologies
nav:
- "개요": index.md
- "설치":
    - "설치 (Mac/Linux)": Installation.md
    - "설치 (Windows/Anaconda)": Installation-Anaconda-Windows.md
- "환경 설계": Learning-Environment-Guide.md
- "훈련":
    - "훈련 워크플로": Training-ML-Agents.md
    - "YAML 설정": Training-Configuration-File.md
    - "PPO 가이드": Training-PPO.md
    - "모방 학습": Training-Imitation-Learning.md
- "인프라":
    - "Docker 사용": Using-Docker.md
- "FAQ": FAQ.md
theme:
  name: material
  palette:
    - primary: blue
    - accent: light blue
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - extra.css
extra_javascript:
  - deprecation-banner.js
markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - attr_list
