behaviors:
  SoccerFives:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 768
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 80000000
    time_horizon: 1500
    summary_freq: 20000
    self_play:
      save_steps: 75000
      team_change: 400000
      swap_steps: 4000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
